### ISSUE TITLE
Invalid cast of function types

### ISSUE THREAD

**Issue by Firobe** [wookey-project/ewok-kernel#1]
IIn the following code
https://github.com/wookey-project/ewok-kernel/blob/c71a6a5c91738e654a01e7670b1803b5d7671810/exti-handler.c#L78
there is a cast from type `user_handler_t` (which is a function taking three parameters) to type `irq_handler_t` (which takes only one parameter).
I get that it is to create a "fake" IRQ cell but it seems very unsafe. Is it a deliberate choice ?

**Comment by PThierry** [comment]
Hello !

Thanks for the issue!

This cast is due to the following:
1)kernel handlers are executed synchronously (i.e. in handler mode) without requiring a stack construct. These handlers only get back the current frame pointer as argument
2) user ISR handlers are postponed and executed in their own context, which include three arguments.

There is no effective bug as the kernel handlers are correctly executed and user and kernel handlers are filtered using other fields of this structure. Although, the method is not clean and may lead to invalid behavior if we don't check correctly what we do in the kernel.

I've patched the code using a dedicated union for handlers, using two fields :
- synchronous_handler, which is executed in handler mode and which get the current frame as argument
- postponed_handler which is postponed through softirq thread and executed in a userspace context, with three arguments

Through this patch, there is no more explicit cast, avoiding any invalid use.

We will make this patch public in a few days, as we are currently finishing the full cleaning of the Wookey project, which include the new kernel version (including a lot of new Ada and Spark content and a lot of kernel patches) and a huge content of userspace drivers and libraries (USB HS/FS, SCSI, hash, cryp, DFU, iso7816 and so on...). We hope the full publication of the project will happen in very few days :-)

**Comment by Firobe** [comment]
Thank you for your answer, I'm looking forward to the release !

**Comment by PThierry** [comment]
Closed with first public full release
